# Generated by Django 5.1.4 on 2025-02-06 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0009_idfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='events.event'),
        ),
    ]
