# Generated by Django 5.1.4 on 2025-02-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_emailverificationcode_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverificationcode',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
