# Generated by Django 5.1.4 on 2025-03-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_created_at_emailverificationcode_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationcode',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='uid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
